name: artifact

on: [push]

env:
  FILE_NAME: hello-server

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build ${{ env.FILE_NAME }} for ubuntu-latest
        run: go build ${{ env.FILE_NAME }}.go

      - name: Build ${{ env.FILE_NAME }} for windows-latest
        run: GOOS=windows GOARCH=amd64 go build -o ${{ env.FILE_NAME }}.exe ${{ env.FILE_NAME }}.go

      - name: Upload artifact for linux
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: ./hello-server

      - name: Upload artifact for windows
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: ./hello-server.exe

  test-linux:
    name: Test Linux
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: linux
          path: .

      - name: Make binary executable
        run: chmod +x ./hello-server

      - name: Run Linux test script
        run: ./test.sh

  test-windows:
    name: Test Windows
    runs-on: windows-latest
    needs: [build]
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: windows
          path: .

      - name: Debug - list files
        run: Get-ChildItem -Recurse

      - name: Run Windows test
        run: .\hello-server.exe
